/* Autogenerated by /usr/bin/halcompile on Sun Feb  6 15:56:37 2022 -- do not edit */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "rtapi_math64.h"

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:bosch_ea:");
MODULE_INFO(linuxcnc, "pin:reset:bit:0:out::None:None");
MODULE_INFO(linuxcnc, "pin:clk:bit:0:out::None:None");
MODULE_INFO(linuxcnc, "pin:outputdata#:bit:8:out::None:None");
MODULE_INFO(linuxcnc, "pin:inputdata#:bit:8:in::None:None");
MODULE_INFO(linuxcnc, "pin:x31-#:bit:8:out::None:None");
MODULE_INFO(linuxcnc, "pin:x32-#:bit:8:out::None:None");
MODULE_INFO(linuxcnc, "pin:x33-#:bit:8:out::None:None");
MODULE_INFO(linuxcnc, "pin:x34-#:bit:8:out::None:None");
MODULE_INFO(linuxcnc, "pin:x35-#:bit:8:out::None:None");
MODULE_INFO(linuxcnc, "pin:x36-#:bit:8:out::None:None");
MODULE_INFO(linuxcnc, "pin:x37-#:bit:8:out::None:None");
MODULE_INFO(linuxcnc, "pin:x38-#:bit:8:out::None:None");
MODULE_INFO(linuxcnc, "pin:x21-#:bit:8:in::None:None");
MODULE_INFO(linuxcnc, "pin:x22-#:bit:8:in::None:None");
MODULE_INFO(linuxcnc, "pin:x23-#:bit:8:in::None:None");
MODULE_INFO(linuxcnc, "pin:x24-#:bit:8:in::None:None");
MODULE_INFO(linuxcnc, "param:resetPeriod:u32:0:r::5:None");
MODULE_INFO(linuxcnc, "param:recoverPeriod:u32:0:r::5:None");
MODULE_INFO(linuxcnc, "param:clkLowPeriod:u32:0:r::5:None");
MODULE_INFO(linuxcnc, "param:samplePeriod:u32:0:r::5:None");
MODULE_INFO(linuxcnc, "funct:_:0:");
MODULE_INFO(linuxcnc, "license:GPL");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state *_next;
    hal_bit_t *reset;
    hal_bit_t *clk;
    hal_bit_t *outputdata[8];
    hal_bit_t *inputdata[8];
    hal_bit_t *x31[8];
    hal_bit_t *x32[8];
    hal_bit_t *x33[8];
    hal_bit_t *x34[8];
    hal_bit_t *x35[8];
    hal_bit_t *x36[8];
    hal_bit_t *x37[8];
    hal_bit_t *x38[8];
    hal_bit_t *x21[8];
    hal_bit_t *x22[8];
    hal_bit_t *x23[8];
    hal_bit_t *x24[8];
    hal_u32_t resetPeriod;
    hal_u32_t recoverPeriod;
    hal_u32_t clkLowPeriod;
    hal_u32_t samplePeriod;
    long elapsed;

};
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;

static void _(struct __comp_state *__comp_inst, long period);
static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    char buf[HAL_NAME_LEN + 1];
    int r = 0;
    int j = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    r = hal_pin_bit_newf(HAL_OUT, &(inst->reset), comp_id,
        "%s.reset", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->clk), comp_id,
        "%s.clk", prefix);
    if(r != 0) return r;
    for(j=0; j < (8); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->outputdata[j]), comp_id,
            "%s.outputdata%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (8); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->inputdata[j]), comp_id,
            "%s.inputdata%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (8); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->x31[j]), comp_id,
            "%s.x31-%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (8); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->x32[j]), comp_id,
            "%s.x32-%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (8); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->x33[j]), comp_id,
            "%s.x33-%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (8); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->x34[j]), comp_id,
            "%s.x34-%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (8); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->x35[j]), comp_id,
            "%s.x35-%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (8); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->x36[j]), comp_id,
            "%s.x36-%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (8); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->x37[j]), comp_id,
            "%s.x37-%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (8); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->x38[j]), comp_id,
            "%s.x38-%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (8); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->x21[j]), comp_id,
            "%s.x21-%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (8); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->x22[j]), comp_id,
            "%s.x22-%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (8); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->x23[j]), comp_id,
            "%s.x23-%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (8); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->x24[j]), comp_id,
            "%s.x24-%01d", prefix, j);
        if(r != 0) return r;
    }
    r = hal_param_u32_newf(HAL_RO, &(inst->resetPeriod), comp_id,
        "%s.resetPeriod", prefix);
    inst->resetPeriod = 5;
    if(r != 0) return r;
    r = hal_param_u32_newf(HAL_RO, &(inst->recoverPeriod), comp_id,
        "%s.recoverPeriod", prefix);
    inst->recoverPeriod = 5;
    if(r != 0) return r;
    r = hal_param_u32_newf(HAL_RO, &(inst->clkLowPeriod), comp_id,
        "%s.clkLowPeriod", prefix);
    inst->clkLowPeriod = 5;
    if(r != 0) return r;
    r = hal_param_u32_newf(HAL_RO, &(inst->samplePeriod), comp_id,
        "%s.samplePeriod", prefix);
    inst->samplePeriod = 5;
    if(r != 0) return r;
    inst->elapsed = 0.0;
    rtapi_snprintf(buf, sizeof(buf), "%s", prefix);
    r = hal_export_funct(buf, (void(*)(void *inst, long))_, inst, 0, 0, comp_id);
    if(r != 0) return r;
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
static int default_count=1, count=0;
RTAPI_MP_INT(count, "number of bosch_ea");
char *names = ""; // comma separated names
RTAPI_MP_STRING(names, "names of bosch_ea");
int rtapi_app_main(void) {
    int r = 0;
    int i;
    comp_id = hal_init("bosch_ea");
    if(comp_id < 0) return comp_id;
    if(count && names[0]) {
        rtapi_print_msg(RTAPI_MSG_ERR,"count= and names= are mutually exclusive\n");
        return -EINVAL;
    }
    if(!count && !names[0]) count = default_count;
    if(count) {
        for(i=0; i<count; i++) {
            char buf[HAL_NAME_LEN + 1];
            rtapi_snprintf(buf, sizeof(buf), "bosch-ea.%d", i);
            r = export(buf, i);
            if(r != 0) break;
       }
    } else {
        int j,idx;
        char *ptr;
        char buf[HAL_NAME_LEN+1];
        ptr = names;
        idx = 0;
        for (i=0,j=0; i <= strlen(names); i++) {
            buf[j] = *(ptr+i);
            if ( (*(ptr+i) == ',') || (*(ptr+i) == 0) ) {
                buf[j] = 0;
                r = export(buf, idx);
                if (*(ptr+i+1) == 0) {break;}
                idx++;
                if(r != 0) {break;}
                j=0;
            } else {
                j++;
            }
        }
    }
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef reset
#define reset (*__comp_inst->reset)
#undef clk
#define clk (*__comp_inst->clk)
#undef outputdata
#define outputdata(i) (*(__comp_inst->outputdata[i]))
#undef inputdata
#define inputdata(i) (0+*(__comp_inst->inputdata[i]))
#undef x31
#define x31(i) (*(__comp_inst->x31[i]))
#undef x32
#define x32(i) (*(__comp_inst->x32[i]))
#undef x33
#define x33(i) (*(__comp_inst->x33[i]))
#undef x34
#define x34(i) (*(__comp_inst->x34[i]))
#undef x35
#define x35(i) (*(__comp_inst->x35[i]))
#undef x36
#define x36(i) (*(__comp_inst->x36[i]))
#undef x37
#define x37(i) (*(__comp_inst->x37[i]))
#undef x38
#define x38(i) (*(__comp_inst->x38[i]))
#undef x21
#define x21(i) (0+*(__comp_inst->x21[i]))
#undef x22
#define x22(i) (0+*(__comp_inst->x22[i]))
#undef x23
#define x23(i) (0+*(__comp_inst->x23[i]))
#undef x24
#define x24(i) (0+*(__comp_inst->x24[i]))
#undef resetPeriod
#define resetPeriod (__comp_inst->resetPeriod)
#undef recoverPeriod
#define recoverPeriod (__comp_inst->recoverPeriod)
#undef clkLowPeriod
#define clkLowPeriod (__comp_inst->clkLowPeriod)
#undef samplePeriod
#define samplePeriod (__comp_inst->samplePeriod)
#undef elapsed
#define elapsed (__comp_inst->elapsed)


#line 32 "bosch_ea.comp"

#include <unistd.h>

typedef enum{
	START,
	RESLOW,
	CLKLOW,
	SAMPLE
} state_t;

static state_t state = START;

FUNCTION (_)
{	
	elapsed++;

	unsigned frame = 0;

	switch (state){
		case START:
			reset = 1;
			clk = 1;
			frame = 0;
			if(elapsed < recoverPeriod){
				break;
			}
			elapsed = 0;
			state = RESLOW;
			break;
		
		case RESLOW:
			clk = 0;
			if(elapsed < resetPeriod){
				break;
			}
			elapsed = 0;
			state = CLKLOW;
			break;

		case CLKLOW:
			clk = 0;
			if(elapsed < clkLowPeriod){
				break;
			}
			elapsed = 0;
			state = SAMPLE;
			break;

		case SAMPLE:
			clk = 1;
			if(elapsed < samplePeriod){
				break;
			}
			elapsed = 0;
			state = CLKLOW;
			switch(frame)
			{
				case 0:
					x31(0) = inputdata(0);
					x31(1) = inputdata(1);
					x31(2) = inputdata(2);
					x31(3) = inputdata(3);
					x31(4) = inputdata(4);
					x31(5) = inputdata(5);
					x31(6) = inputdata(6);
					x31(7) = inputdata(7);
					frame++;
					break;

				case 1:
					x32(0) = inputdata(0);
					x32(1) = inputdata(1);
					x32(2) = inputdata(2);
					x32(3) = inputdata(3);
					x32(4) = inputdata(4);
					x32(5) = inputdata(5);
					x32(6) = inputdata(6);
					x32(7) = inputdata(7);
					frame++;
					break;

				case 2:
					x33(0) = inputdata(0);
					x33(1) = inputdata(1);
					x33(2) = inputdata(2);
					x33(3) = inputdata(3);
					x33(4) = inputdata(4);
					x33(5) = inputdata(5);
					x33(6) = inputdata(6);
					x33(7) = inputdata(7);
					frame++;
					break;

				case 3:
					x34(0) = inputdata(0);
					x34(1) = inputdata(1);
					x34(2) = inputdata(2);
					x34(3) = inputdata(3);
					x34(4) = inputdata(4);
					x34(5) = inputdata(5);
					x34(6) = inputdata(6);
					x34(7) = inputdata(7);
					frame++;
					break;

				case 4:
					x35(0) = inputdata(0);
					x35(1) = inputdata(1);
					x35(2) = inputdata(2);
					x35(3) = inputdata(3);
					x35(4) = inputdata(4);
					x35(5) = inputdata(5);
					x35(6) = inputdata(6);
					x35(7) = inputdata(7);
					frame++;
					break;

				case 5:
					x36(0) = inputdata(0);
					x36(1) = inputdata(1);
					x36(2) = inputdata(2);
					x36(3) = inputdata(3);
					x36(4) = inputdata(4);
					x36(5) = inputdata(5);
					x36(6) = inputdata(6);
					x36(7) = inputdata(7);
					frame++;
					break;

				case 6:
					x37(0) = inputdata(0);
					x37(1) = inputdata(1);
					x37(2) = inputdata(2);
					x37(3) = inputdata(3);
					x37(4) = inputdata(4);
					x37(5) = inputdata(5);
					x37(6) = inputdata(6);
					x37(7) = inputdata(7);
					frame++;
					break;

				case 7:
					x38(0) = inputdata(0);
					x38(1) = inputdata(1);
					x38(2) = inputdata(2);
					x38(3) = inputdata(3);
					x38(4) = inputdata(4);
					x38(5) = inputdata(5);
					x38(6) = inputdata(6);
					x38(7) = inputdata(7);
					frame++;
					break;

				default:
					frame = 0;
					state = START;
					// clk = 0;
			}
			// clk = 0;
			break;
	}
}

static int __comp_get_data_size(void) { return 0; }
